[Unit]
RequiresMountsFor=/var/lib/user-data /var/run/cdi/nvidia.yaml
After=containerd.service nvidia-cdi-generate.service var-lib-user\x2ddata.mount
Wants=containerd.service nvidia-cdi-generate.service

[Service]
ExecStartPre=/usr/bin/install -d -m 0711 /var/lib/user-data/docker
